Mle improoooovments
4teamwork/ftw.sliderblock pull request #26
Opened 2016-10-20 07:13 UTC by maethu

This PR needs https://github.com/4teamwork/ftw.simplelayout/pull/392

Major changes
- Upload panes using quickupload
- Edit panes directly in the slider block

Watch this:
![slider](https://cloud.githubusercontent.com/assets/437933/19549603/80f0372e-96a5-11e6-9021-37f9475a1783.gif)

2016-10-20 10:19 UTC, jone requested changes

2016-10-20 10:19 UTC, jone commented on docs/HISTORY.txt
> +- This release needs at lease ftw.simplelayout 1.12.0.
🚧 This should be declared in the dependencies (`ftw.simplelayout [contenttypes] >= 1.12.0`) as soon as `ftw.simplelayout` is released.

2016-10-20 10:19 UTC, jone commented on ftw/sliderblock/browser/resources/styles.scss
> +
The icon is often barely visible, depending on the image:
<img width="1201" alt="bildschirmfoto 2016-10-20 um 12 15 57" src="https://cloud.githubusercontent.com/assets/7469/19555952/2cb41e5e-96bf-11e6-87e0-032c203ad2ba.png">

I propose to use a ligther text color and apply a dark outer glow effect for having more contrast, making the icon better visible on most images, without having to apply a background color or moving the icon out of the image.
```css
  &:before {
    color: #EEE;
    text-shadow: 1px 0px 1px rgba(136, 136, 136, 0.7), 0px 1px 1px rgba(136, 136, 136, 0.7), -1px 0px 1px rgba(136, 136, 136, 0.7), 0px -1px 1px rgba(136, 136, 136, 0.7);
  }
  &:hover:before {
    color: #FFF;
    text-shadow: 1px 0px 1px rgba(136, 136, 136, 1), 0px 1px 1px rgba(136, 136, 136, 1), -1px 0px 1px rgba(136, 136, 136, 1), 0px -1px 1px rgba(136, 136, 136, 1);
  }
```
<img width="1207" alt="bildschirmfoto 2016-10-20 um 12 16 28" src="https://cloud.githubusercontent.com/assets/7469/19555971/44aea97a-96bf-11e6-9bd2-e0bc856acda1.png">

2016-10-21 06:11 UTC, maethu commented on docs/HISTORY.txt
> +- This release needs at lease ftw.simplelayout 1.12.0.
Yep I'll do that, I'm no yet sure if it is 1.12.0, or something else 😉

2016-10-21 06:14 UTC, maethu commented on ftw/sliderblock/browser/resources/styles.scss
> +
@jone Probably a white slightly opac background, with a dark icon would be the best. Now it's also hard to see on the image with house/tree

2016-10-21 08:04 UTC, maethu commented on docs/HISTORY.txt
> +- This release needs at lease ftw.simplelayout 1.12.0.
@jone add the requirement 1.12.0 it is :-)

2016-10-21 13:29 UTC, jone approved these changes

2016-10-21 13:29 UTC, merged